# Generated by Django 2.0.5 on 2018-06-02 10:37

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('coin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=3, max_digits=13)),
                ('high', models.DecimalField(decimal_places=3, max_digits=13)),
                ('low', models.DecimalField(decimal_places=3, max_digits=13)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment', models.DecimalField(decimal_places=3, default=0, max_digits=13, max_length=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coins_bought', models.DecimalField(decimal_places=8, default=0, max_digits=13, max_length=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coin_value', models.DecimalField(decimal_places=3, max_digits=13, max_length=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('on_time', models.DateTimeField(default=datetime.datetime.now)),
                ('coin', models.ForeignKey(db_column='coin', on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1024)),
                ('channel', models.CharField(max_length=15)),
                ('user_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_detail', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notifyjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='notifyjob',
            unique_together={('user', 'coin')},
        ),
    ]
