# Generated by Django 2.0.5 on 2018-06-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyjob',
            name='coin_value',
            field=models.DecimalField(decimal_places=3, max_digits=13, max_length=20),
        ),
        migrations.AlterField(
            model_name='notifyjob',
            name='coins_bought',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=13, max_length=20),
        ),
        migrations.AlterField(
            model_name='notifyjob',
            name='investment',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13, max_length=20),
        ),
    ]
