# Generated by Django 2.0.5 on 2018-06-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180602_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifyjob',
            name='coin_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=13, max_length=20),
        ),
    ]
